name: CI
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Set up Go development environment
        uses: actions/setup-go@v1
        with:
          go-version: '1.15'
      - name: Build artefacts
        run: |
          make clean
          make all
      - name: Upload artefacts
        uses: actions/upload-artifact@v2-preview
        with:
          name: entropyd
          path: bin/*
